[package]
name = "spotifyrics"
version = "0.1.0"
authors = ["Gabriele <gabriele.belluardo@outlook.it>"]
edition = "2018"

[dependencies]
rspotify = "0.10.0"
scraper = "0.12.0"
reqwest = "0.10.7"
dotenv = "0.15.0"

[dependencies.tokio]
version = "0.2.22"
features = ["fs", "macros", "process"]
